"""
Code Executor Module
Generates executable Python code files that can be downloaded and run
"""

import os
from datetime import datetime
import hashlib


def create_executable_code(code: str, topic: str, include_example: bool = True) -> dict:
    """
    Create a Python file with the generated code
    
    Args:
        code (str): The Python code to save
        topic (str): The topic name for the file
        include_example (bool): Whether to include example usage
        
    Returns:
        dict: Contains 'success' status, 'filepath', 'filename', and optional 'error'
    """
    try:
        if not code or len(code.strip()) == 0:
            return {
                'success': False,
                'error': 'No code provided'
            }
        
        # Clean the code (remove markdown code blocks if present)
        cleaned_code = clean_code_block(code)
        
        # Create filename from topic
        safe_topic = "".join(c if c.isalnum() else "_" for c in topic.lower())
        timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
        filename = f'{safe_topic}_{timestamp}.py'
        
        # Define output path
        code_dir = 'generated_code'
        os.makedirs(code_dir, exist_ok=True)
        filepath = os.path.join(code_dir, filename)
        
        # Add header comments
        header = f"""\"\"\"
Machine Learning Code: {topic}
Generated by ML Learning Assistant
Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

This code is for educational purposes.
Make sure to install required dependencies before running.
\"\"\"

"""
        
        # Add example usage template if requested and not already present
        if include_example and 'if __name__' not in cleaned_code:
            example_template = """

# Example Usage
if __name__ == "__main__":
    print("Running ML code example...")
    # Add your test code here
    pass
"""
            full_code = header + cleaned_code + example_template
        else:
            full_code = header + cleaned_code
        
        # Write to file
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(full_code)
        
        return {
            'success': True,
            'filepath': filepath,
            'filename': filename,
            'message': 'Code file created successfully',
            'download_url': f'/download/code/{filename}'
        }
        
    except Exception as e:
        return {
            'success': False,
            'error': f'Error creating code file: {str(e)}'
        }


def clean_code_block(code: str) -> str:
    """
    Remove markdown code block syntax if present
    
    Args:
        code (str): Raw code that might contain markdown syntax
        
    Returns:
        str: Cleaned code without markdown syntax
    """
    lines = code.split('\n')
    cleaned_lines = []
    in_code_block = False
    
    for line in lines:
        # Skip markdown code block delimiters
        if line.strip().startswith('```'):
            in_code_block = not in_code_block
            continue
        cleaned_lines.append(line)
    
    return '\n'.join(cleaned_lines)


def validate_python_syntax(code: str) -> dict:
    """
    Validate Python code syntax without executing it
    
    Args:
        code (str): Python code to validate
        
    Returns:
        dict: Contains 'success' status and validation results
    """
    try:
        # Clean the code first
        cleaned_code = clean_code_block(code)
        
        # Try to compile the code
        compile(cleaned_code, '<string>', 'exec')
        
        return {
            'success': True,
            'valid': True,
            'message': 'Code syntax is valid'
        }
        
    except SyntaxError as e:
        return {
            'success': True,
            'valid': False,
            'error': f'Syntax error at line {e.lineno}: {e.msg}',
            'line': e.lineno
        }
        
    except Exception as e:
        return {
            'success': True,
            'valid': False,
            'error': f'Validation error: {str(e)}'
        }


def generate_colab_notebook(code: str, topic: str) -> dict:
    """
    Generate a Google Colab compatible notebook JSON
    
    Args:
        code (str): Python code to include in the notebook
        topic (str): Topic name for the notebook
        
    Returns:
        dict: Contains notebook JSON structure
    """
    try:
        cleaned_code = clean_code_block(code)
        
        # Create Jupyter notebook structure
        notebook = {
            "nbformat": 4,
            "nbformat_minor": 0,
            "metadata": {
                "colab": {
                    "name": f"{topic}.ipynb",
                    "provenance": []
                },
                "kernelspec": {
                    "name": "python3",
                    "display_name": "Python 3"
                },
                "language_info": {
                    "name": "python"
                }
            },
            "cells": [
                {
                    "cell_type": "markdown",
                    "metadata": {},
                    "source": [
                        f"# {topic}\\n",
                        "\\n",
                        "Generated by ML Learning Assistant\\n",
                        "\\n",
                        "This notebook contains code for educational purposes."
                    ]
                },
                {
                    "cell_type": "code",
                    "metadata": {},
                    "source": cleaned_code.split('\n'),
                    "execution_count": None,
                    "outputs": []
                }
            ]
        }
        
        return {
            'success': True,
            'notebook': notebook,
            'message': 'Colab notebook structure generated'
        }
        
    except Exception as e:
        return {
            'success': False,
            'error': f'Error generating notebook: {str(e)}'
        }


def get_code_statistics(code: str) -> dict:
    """
    Get basic statistics about the generated code
    
    Args:
        code (str): Python code to analyze
        
    Returns:
        dict: Code statistics including line count, imports, functions, etc.
    """
    try:
        cleaned_code = clean_code_block(code)
        lines = cleaned_code.split('\n')
        
        stats = {
            'total_lines': len(lines),
            'code_lines': len([l for l in lines if l.strip() and not l.strip().startswith('#')]),
            'comment_lines': len([l for l in lines if l.strip().startswith('#')]),
            'blank_lines': len([l for l in lines if not l.strip()]),
            'imports': len([l for l in lines if l.strip().startswith('import') or l.strip().startswith('from')]),
            'functions': len([l for l in lines if l.strip().startswith('def ')]),
            'classes': len([l for l in lines if l.strip().startswith('class ')])
        }
        
        return {
            'success': True,
            'statistics': stats
        }
        
    except Exception as e:
        return {
            'success': False,
            'error': f'Error calculating statistics: {str(e)}'
        }
